name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew clean build

      - name: List build artifacts
        run: ls -R build/libs

      - name: Build & Push Docker Image
#        if: github.event.pull_request.merged == true || github.ref == 'refs/heads/master'
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: mansooreh26/mypersonalproject
          registry: docker.io
          dockerfile: Dockerfile
          tags: latest-${{ github.run_number }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  delete-branch:
    needs: [build]
    if: github.event.pull_request.merged == true || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Delete merged branches
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          branches=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/pulls?state=closed \
            | jq -r '.[] | select(.merged_at != null) | .head.ref')
          for branch in $branches; do
            if [ "$branch" != "master" ]; then
              echo "Deleting branch $branch"
              curl -s -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
                https://api.github.com/repos/${{ github.repository }}/git/refs/heads/$branch
            fi
          done
